### ISSUE TITLE
Issues with Threading GDAL

### ISSUE THREAD

**Issue by flippmoke** [mapbox/gdal-tiling-bench#1]
We are going to have big problems with any performant multithreading of TIFFs in GDAL. My last attempted led me down the path of [this](https://github.com/OSGeo/gdal/pull/39/files) and [this](https://trac.osgeo.org/gdal/wiki/rfc47_dataset_caching). After lots of changes this only really allowed multithreaded read safe processing on memory datasets. I was planning on expanding the scope of the RFC to make multithreading safe processing across all of GDAL and its drivers.

The discussions for this can be found:
- [Starting here](http://lists.osgeo.org/pipermail/gdal-dev/2014-August/039769.html)
- [continued in another thread here](http://lists.osgeo.org/pipermail/gdal-dev/2014-August/039868.html)
- [and here](http://lists.osgeo.org/pipermail/gdal-dev/2014-August/039881.html)
- [and also here](http://lists.osgeo.org/pipermail/gdal-dev/2014-August/039944.html)

So the core issues in GDAL associated with this are:
- Thread safety of global objects
- Thread safety of the block cache (which isn't currently block safe)
- Thread safety of the individual dataset object (many operations around it are not thread safe)
- Thread safety of the drivers (TIFF isn't thread safe)
- Thread safety of individual file handlers (inside each driver)

I have ideas on how to solve all of these problems, but this is a HUGE effort, and will require a lot of thinking and help/support from the GDAL community.

/cc @springmeyer

**Comment by springmeyer** [comment]
Yes, definitely going to be interesting to see what we learn. @rouault is taking a look at the benchmark and has some concrete ideas for us to try. So let's create new tickets as we flesh those ideas out. Will close this now but will be great to refer back to.
