### ISSUE TITLE
Output data into JSON for visualization

### ISSUE THREAD

**Issue by mapsam** [mapbox/gdal-tiling-bench#11]
It would be really neat to store all of the information we're printing to the console into a `data.json` file so we can visualize it. I'm imagining something like this table that just looks at speeds against versions and different fixture data:

<img width="793" alt="screen shot 2016-01-29 at 4 52 51 pm" src="https://cloud.githubusercontent.com/assets/1943001/12692191/c30121b4-c6a8-11e5-9f77-fe4de37732b2.png">

**Comment by springmeyer** [comment]
\o/

**Comment by mapsam** [comment]
Woot - here's a first pass (at least in a table) that gives us the benchmark information across versions and file types:

https://s3.amazonaws.com/mapbox/playground/mapsam/index.html?1454446545
