### ISSUE TITLE
Rename this repo to mapnik-bench

### ISSUE THREAD

**Issue by mapsam** [mapbox/gdal-tiling-bench#12]
We are starting to move strictly into the `mapnik` version world here, and the `gdal-tiling-bench` name lives on. What's the protocol for updating this @springmeyer?

**Comment by springmeyer** [comment]
@mapsam - just go into the settings and rename to something like `node-mapnik-bench` or `node-mapnik-tiling-bench`. Then to finish the migration also strip the readme of all the old gdal specific stuff.

**Comment by mapsam** [comment]
renamed to `node-mapnik-bench`, will update README in a future update!
