### ISSUE TITLE
points-1000 fails in v2_spec

### ISSUE THREAD

**Issue by mapsam** [mapbox/gdal-tiling-bench#14]
Getting this error:

```
~/mapbox/gdal-tiling-bench[visualize]$ node test.js testcases/geojson/points-1000/map.xml mapnik-versions/v2_spec/

Config -> using node v0.10.40
Config -> using mapnik at /Users/mapsam/mapbox/gdal-tiling-bench/mapnik-versions/v2_spec/node_modules/mapnik/lib/mapnik.js
Config -> source options: {"close":true,"minzoom":0,"maxzoom":4,"bounds":[-179.4798170775175,-89.94831437710673,179.27351941354573,89.85857545863837],"type":"pyramid"}
Config -> threadpool size: 6
Config -> sink: noop://

/Users/mapsam/mapbox/gdal-tiling-bench/mapnik-versions/v2_spec/node_modules/tilelive-bridge/index.js:260
    map.render(new mapnik.VectorTile(+z,+x,+y), opts, function(err, image) {
               ^
TypeError: required parameters (z, x, and y) must be greater then or equal to zero
    at Function.Bridge.getVector (/Users/mapsam/mapbox/gdal-tiling-bench/mapnik-versions/v2_spec/node_modules/tilelive-bridge/index.js:260:16)
    at /Users/mapsam/mapbox/gdal-tiling-bench/mapnik-versions/v2_spec/node_modules/tilelive-bridge/index.js:174:20
    at /Users/mapsam/mapbox/gdal-tiling-bench/mapnik-versions/v2_spec/node_modules/tilelive-bridge/node_modules/mapnik-pool/node_modules/generic-pool/lib/generic-pool.js:291:11
    at loaded (/Users/mapsam/mapbox/gdal-tiling-bench/mapnik-versions/v2_spec/node_modules/tilelive-bridge/node_modules/mapnik-pool/index.js:27:28)
```

**Comment by mapsam** [comment]
I think this is related to a bounding box issue in `tilelive-bridge` because this only happens when the extent of the geoms is near 100% of the world. It could potentially be a rounding error when `89.89` is rounded up to `90` degrees.

@jakepruitt noticed the `y` value was `-1` in this case, which means it's not calculating properly.

For now, going to remove all `point-XXXX` cases that are generated with geojson.io random points and hit the bounding extents.

**Comment by springmeyer** [comment]
Odd error, thanks for reporting.

> For now, going to remove all point-XXXX cases that are generated with geojson.io random points and hit the bounding extents.

Sounds like a good workaround for now.

**Comment by mapsam** [comment]
Upon further inspection from @jakepruitt this issue deals with the `sphericalmercator` (SM) bounds. SM covers only `85.05` degrees north and south, which means a lot of our "random point" fixtures have data outside of those coordinates near 90 degrees, and giving us a `-1` value for `y` when passing as parameters, which fails in tilelive-bridge.

**Comment by jakepruitt** [comment]
This PR should fix up this issue: https://github.com/mapbox/tilelive/pull/161
