### ISSUE TITLE
Migrate all s3 downloads to a common bucket

### ISSUE THREAD

**Issue by mapsam** [mapbox/gdal-tiling-bench#9]
Right now we have things in `springmeyer` personal and `mapbox/playground/mapsam`. Something like `mapbox/mapnik-bench`?

**Comment by springmeyer** [comment]
:+1: How about `mapbox/playground/mapnik-bench/`?

**Comment by mapsam** [comment]
What's the likelihood that `playground` could get removed? @dnomadb mentioned it isn't a permanent spot. So maybe create a new directory `mapbox/mapnik-bench`?

**Comment by mapsam** [comment]
Working in `mapbox/node-mapnik-bench`
